api: [spigot-plugin, paper-plugin, bukkit-plugin]
name: HorseEggs
version: ${version}
api-version: 1.20.6
description: Horses can be captured and released. Display the captured horse's jumping power and speed information.
load: STARTUP
author: wackyls6
website: https://github.com/wackyls6/HorseEggs
main: wacky.horseeggs.HorseEggs
database: false
depend: [Logger, Rtag]
#prefix: 
softdepend: [WorldGuard]
#loadbefore: 
#commands: 
permissions:
    horseeggs.*:
        description: Gives access to all HorseEggs use.
        children:
#            horseeggs.capture: true
#            horseeggs.release: true
            horseeggs.capture:
                description: Capture a horse into an egg.
                default: true
            horseeggs.release:
                description: Release the horse to horseeggs.
                default: true
