name: HorseEggs
main: wacky.horseeggs.HorseEggs
version: ${version}
author: wackyls6
api-version: 1.20
depend: [Logger]
permissions:
    horseeggs.*:
        description:
            children:
                horseeggs.capture: true
                horseeggs.release: true
    horseeggs.capture:
        description: capture a horse into an egg
        default: true
    horseeggs.release:
        description: release the horse to horseeggs
        default: true
