name: HorseEggs
main: wacky.horseeggs.HorseEggs
version: 1.1.0
author: wackyls6
permissions:
    horseeggs.*:
        description:
            children:
                horseeggs.capture: true
                horseeggs.release: true
    horseeggs.capture:
        description: capture a horse into an egg
        default: true
    horseeggs.release:
        description: release the horse to horseeggs
        default: true
